### ISSUE TITLE
16kHz for vqw2v_extractor and wavlm_extractor

### ISSUE THREAD

**Issue by abylouw** [cantabile-kwok/vec2wav2.0#5]
Hi,

Thank you for sharing your work in this repository. I have managed to start the training on my own data with some changes due to sampling rate problems.

The default config is for 24kHz but it seems that both the vqw2v_extractor and wavlm_extractor require 16kHz without checking the actual sampling rate whilst the mel features do take an input sampling rate in extract_fbank.sh. This creates a problem in `__getitem__` in scp_dataset.py, which checks the length of mel, vqidx and prompt.

**Comment by cantabile-kwok** [comment]
Ah, I see. Since I extracted everything with a 16kHz version, I overlooked the sampling rate. I think it should be OK if the SSL extractors automatically check and sampling rate and convert to 16kHz. Thank you for finding this and your PR!

**Comment by cantabile-kwok** [comment]
[This commit](https://github.com/cantabile-kwok/vec2wav2.0/commit/2e6c9b38d818f902b5aa5ffb641eb254abd2f2d9) is expected to fix this bug. Now we only have to provide 24kHz audio path.
