### ISSUE TITLE
Training losses

### ISSUE THREAD

**Issue by abylouw** [cantabile-kwok/vec2wav2.0#6]
Can you maybe share your tensorboard of your training losses? I would just like to compare to my own.

![Snapshot_2024-11-10_07-48-38](https://github.com/user-attachments/assets/39e7fafd-c561-47c4-a7ed-bff15af305af)

**Comment by cantabile-kwok** [comment]
I think your loss goes normal. Here are my logs: https://drive.google.com/file/d/10CTkCEjC_ReNAgDBaPfP50OiqmdBuhSQ/view?usp=sharing.

Please tell me if this link does not work.

**Comment by abylouw** [comment]
Thank you very much, I have downloaded it.
