### ISSUE TITLE
missing codebook.npy

### ISSUE THREAD

**Issue by indiejoseph** [cantabile-kwok/vec2wav2.0#7]
After followed the instruction in data_prep for my custom dataset, there still missing the codebook.npy file, how can I get it?

**Comment by cantabile-kwok** [comment]
Ah, I missed this instruction since the codebook can be downloaded together if vq indexes are downloaded rather than locally extracted. I have updated `data_prep.md`. The codebook can be obtained by:
```python
from vec2wav2.ssl_models.vqw2v_extractor import Extractor
import numpy as np
extractor = Extractor()   # provide checkpoint or device arguments if needed
codebook = extractor.get_codebook()
np.save("feats/vqidx/codebook.npy", codebook)
```

**Comment by indiejoseph** [comment]
Thanks for your quick response!
