### ISSUE TITLE
Config file config.yml

### ISSUE THREAD

**Issue by badrex** [cantabile-kwok/vec2wav2.0#8]
Hi there, 

Thanks a lot for sharing your model. The demo looks very interesting and the generated samples sound very natural. Great work!  💯 

I tried to run the code on my local machine, but I could not figure out what should be in **config.yml** below

pretrained/
    - vq-wav2vec_kmeans.pt 
    - WavLM-Large.pt 
    - generator.ckpt
    - **config.yml**
   
Could you perhaps provide an example of the (default) parameters in this file? 

Thanks a lot in advance :)

**Comment by cantabile-kwok** [comment]
Thanks so much for your kind words! The config.yml can be found at our [huggingface repo](https://huggingface.co/cantabile-kwok/vec2wav2.0/tree/main):
<img width="889" alt="image" src="https://github.com/user-attachments/assets/baaa66d1-db7d-4957-a450-ecf9de144b84">

**Comment by badrex** [comment]
Thank you very much! It works now 👍🏼
